"""
Marketing Research Agent.

Two work streams:
1. General scan — fixed web searches on broad art marketing topics
2. Targeted monitoring — per-strategy searches generated by the LLM from each doc

Run via: uv run python -m src.marketing.run_research
"""
import logging
from datetime import date
from pathlib import Path

from langchain_core.messages import HumanMessage

from src.tools.marketing_db import (
    get_all_strategies,
    save_research_finding,
)
from src.tools.search import web_search

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).parent.parent.parent


def _general_queries() -> list[str]:
    year = date.today().year
    return [
        f"art marketing strategies for painters {year}",
        "how to sell original paintings online Europe",
        "plein air painting marketing visibility strategies",
        "selling fine art at markets Germany Bavaria",
        "Instagram marketing for fine art painters",
        f"art galleries Germany emerging artists open submissions {year}",
    ]


def _read_doc(doc_path: str) -> str:
    if not doc_path:
        return ""
    full_path = REPO_ROOT / doc_path
    if not full_path.exists():
        return ""
    return full_path.read_text(encoding="utf-8")[:3000]


def _get_monitoring_queries(llm, strategy_name: str, doc_content: str) -> list[str]:
    """Ask the LLM what to search for given this strategy doc."""
    if not doc_content.strip():
        return []
    prompt = f"""Given this marketing strategy document for artist Christopher Rehm, identify 2 specific
web search queries worth running this week — things to monitor: specific websites to check for updates,
application deadlines, events, regulatory changes, or opportunities mentioned in the doc.

Strategy: {strategy_name}

Document:
{doc_content}

Reply with exactly 2 search queries, one per line, no numbering or bullets. Just the queries."""

    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        lines = [line.strip() for line in response.content.strip().splitlines() if line.strip()]
        return lines[:2]
    except Exception as e:
        logger.warning("research_agent: monitoring query generation failed for '%s': %s", strategy_name, e)
        return []


def _synthesize_findings(llm, query: str, results: list[dict]) -> str | None:
    """Summarize search results into a 2-3 sentence finding."""
    if not results:
        return None
    snippets = "\n".join(
        f"- {r['title']}: {r.get('snippet', '')[:200]}" for r in results[:5]
    )
    prompt = f"""Summarize these web search results in 2-3 sentences for artist Christopher Rehm.
Focus on anything actionable or relevant to marketing original artwork.
If results are irrelevant or empty, reply with exactly: SKIP

Search query: {query}

Results:
{snippets}"""

    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        summary = response.content.strip()
        if summary == "SKIP" or len(summary) < 20:
            return None
        return summary
    except Exception as e:
        logger.warning("research_agent: synthesis failed for query '%s': %s", query[:50], e)
        return None


def run(llm) -> int:
    """
    Run the research agent. Returns total number of findings saved.
    `llm` is a LangChain BaseChatModel (use CHEAP_LLM).
    """
    today = str(date.today())
    total_saved = 0
    general_queries = _general_queries()

    # --- Work stream 1: General scan ---
    logger.info("research_agent: running %d general queries", len(general_queries))
    for query in general_queries:
        try:
            results = web_search(query, max_results=5)
        except Exception as e:
            logger.warning("research_agent: web_search failed for '%s': %s", query[:50], e)
            continue
        summary = _synthesize_findings(llm, query, results)
        if summary:
            source_url = results[0]["url"] if results else None
            save_research_finding(
                run_date=today,
                topic=query[:100],
                summary=summary,
                source_url=source_url,
                strategy_id=None,
            )
            total_saved += 1
            logger.info("research_agent: saved general finding for '%s'", query[:50])

    # --- Work stream 2: Targeted monitoring per strategy ---
    strategies = get_all_strategies(status="active")
    for s in strategies:
        doc_content = _read_doc(s["doc_path"])
        queries = _get_monitoring_queries(llm, s["name"], doc_content)
        logger.info(
            "research_agent: %d targeted queries for strategy '%s'",
            len(queries), s["name"]
        )
        for query in queries:
            try:
                results = web_search(query, max_results=5)
            except Exception as e:
                logger.warning("research_agent: web_search failed for '%s': %s", query[:50], e)
                continue
            summary = _synthesize_findings(llm, query, results)
            if summary:
                source_url = results[0]["url"] if results else None
                save_research_finding(
                    run_date=today,
                    topic=query[:100],
                    summary=summary,
                    source_url=source_url,
                    strategy_id=s["id"],
                )
                total_saved += 1
                logger.info(
                    "research_agent: saved targeted finding for strategy '%s'",
                    s["name"]
                )

    logger.info("research_agent: done — %d findings saved", total_saved)
    return total_saved
